// Session identity for the self-host oma-vault outbound proxy.
//
// Sandbox adapters point HTTP(S)_PROXY at oma-vault with the session's
// identity embedded as proxy credentials (`http://metadata:<b64 tags>@host:port`,
// the socket-metadata shape mockttp exposes to handlers as `req.tags`).
// The token is HMAC-signed (see @open-managed-agents/vault-forward/proxy-token)
// so a sandbox cannot forge another session's identity by guessing ids.
//
// Key resolution (shared with oma-vault):
//   OMA_VAULT_PROXY_SECRET → PLATFORM_ROOT_SECRET → key file
//   (OMA_VAULT_PROXY_KEY_FILE, default `<dirname(OMA_VAULT_CA_CERT)>/proxy-token.key`,
//   generated by oma-vault on first boot).
// When no key is available we return the proxy URL WITHOUT identity: oma-vault
// then treats the traffic as anonymous and injects no credentials (secure
// default) — we log once so the operator can see why injection isn't happening.

import {
  defaultProxyKeyFileForCaCert,
  resolveProxyTokenKey,
  signProxyToken,
  proxyAuthCredentials,
  type ResolvedProxyKey,
} from "@open-managed-agents/vault-forward/proxy-token";
import { getLogger } from "@open-managed-agents/observability";

const log = getLogger("outbound-proxy");
let cachedKey: ResolvedProxyKey | null = null;
let warnedNoKey = false;

function resolveSignerKey(env: Record<string, string | undefined>): Uint8Array | null {
  if (cachedKey) return cachedKey.key;
  let resolved: ResolvedProxyKey | null = null;
  try {
    resolved = resolveProxyTokenKey({
      env,
      keyFile: defaultProxyKeyFileForCaCert(env.OMA_VAULT_CA_CERT),
    });
  } catch (err) {
    log.warn({ op: "outbound_proxy.key_error", err }, `proxy token key resolution failed: ${(err as Error).message}`);
  }
  if (!resolved) {
    if (!warnedNoKey) {
      warnedNoKey = true;
      log.warn(
        { op: "outbound_proxy.no_key" },
        "no oma-vault proxy signing key (set PLATFORM_ROOT_SECRET or OMA_VAULT_PROXY_SECRET on both " +
          "main-node and oma-vault, or share OMA_VAULT_PROXY_KEY_FILE); sandbox traffic will reach " +
          "oma-vault without a session identity and receive no credential injection",
      );
    }
    return null;
  }
  // Cache hits only; a missing key is re-resolved next time (the key file
  // may appear once oma-vault finishes booting).
  cachedKey = resolved;
  log.info({ op: "outbound_proxy.key_source", source: resolved.source }, `oma-vault proxy tokens signed with key from ${resolved.source}`);
  return resolved.key;
}

/** Test hook — drop the memoized signer key. */
export function resetOutboundProxyKeyCache(): void {
  cachedKey = null;
  warnedNoKey = false;
}

export function withSessionProxyContext(
  proxyUrl: string,
  opts?: { tenantId: string; sessionId: string },
  signing?: { key?: Uint8Array; env?: Record<string, string | undefined> },
): string {
  if (!opts?.tenantId || !opts.sessionId) return proxyUrl;
  const key = signing?.key ?? resolveSignerKey(signing?.env ?? process.env);
  if (!key) return proxyUrl;
  try {
    const url = new URL(proxyUrl);
    const creds = proxyAuthCredentials(
      signProxyToken(key, { tenantId: opts.tenantId, sessionId: opts.sessionId }),
    );
    url.username = creds.username;
    url.password = creds.password;
    return url.toString();
  } catch (err) {
    log.warn({ op: "outbound_proxy.sign_failed", err }, `failed to sign proxy token: ${(err as Error).message}`);
    return proxyUrl;
  }
}
